### ISSUE TITLE
"Wann darf er das?"

### ISSUE THREAD

**Issue by DerZyklop** [molily/javascript-einfuehrung#3]
[Hier](https://github.com/molily/javascript-einfuehrung/blob/master/funktionen.html#L35) steht: _TODO: Wann darf er das?_

Ich wüsste nicht, dass es irgendeinen Fall gibt, in dem ein Bezeichner ein Leerzeichen enthalten darf. Würde den TODO-Kommentar also entfernen.

**Comment by molily** [comment]
Danke, habe ich korrigiert. Ich habe ganzen den Abschnitt überarbeitet:

https://molily.de/js/variablen.html#bezeichner
